"""user provisioning flags

Revision ID: 06c94bdb1212
Revises: 5abc175e28ff
Create Date: 2026-08-18 21:43:49.304742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c94bdb1212'
down_revision: Union[str, Sequence[str], None] = '5abc175e28ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_provisioned', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('force_password_change')
        batch_op.drop_column('auto_provisioned')

    # ### end Alembic commands ###
