"""drop custom field tables and call record AI placeholder columns

Revision ID: 1eb13d95d360
Revises: 627e7884c03e
Create Date: 2026-08-18 17:02:16.494921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb13d95d360'
down_revision: Union[str, Sequence[str], None] = '627e7884c03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_field_values')
    op.drop_table('custom_field_definitions')
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_column('summary_text')
        batch_op.drop_column('transcript_text')
        batch_op.drop_column('follow_up_required')
        batch_op.drop_column('ai_result_json')
        batch_op.drop_column('sentiment')
        batch_op.drop_column('recording_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recording_path', sa.VARCHAR(length=500), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('sentiment', sa.VARCHAR(length=80), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('ai_result_json', sa.TEXT(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('follow_up_required', sa.BOOLEAN(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('transcript_text', sa.TEXT(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('summary_text', sa.TEXT(), nullable=False, server_default=''))

    op.create_table('custom_field_definitions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=32), nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('custom_field_values',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('definition_id', sa.INTEGER(), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('value_text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['custom_field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'entity_type', 'entity_id', name=op.f('uq_custom_field_values_target'))
    )
    # ### end Alembic commands ###
