"""sms notifications table and scan schedule sms toggle

Revision ID: 37b8da0080f6
Revises: 06c94bdb1212
Create Date: 2026-08-18 22:00:43.318619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b8da0080f6'
down_revision: Union[str, Sequence[str], None] = '06c94bdb1212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_task_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_task_id'], ['call_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_notifications_call_task_id'), ['call_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_notifications_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_notifications_status'), ['status'], unique=False)

    with op.batch_alter_table('scan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_schedules', schema=None) as batch_op:
        batch_op.drop_column('sms_enabled')

    with op.batch_alter_table('sms_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_sms_notifications_phone'))
        batch_op.drop_index(batch_op.f('ix_sms_notifications_call_task_id'))

    op.drop_table('sms_notifications')
    # ### end Alembic commands ###
