"""scan schedule script template reference

Revision ID: 5abc175e28ff
Revises: 78b35e30ea36
Create Date: 2026-08-18 17:32:04.634348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abc175e28ff'
down_revision: Union[str, Sequence[str], None] = '78b35e30ea36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('script_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(op.f('fk_scan_schedules_script_id_scripts'), 'scripts', ['script_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_scan_schedules_script_id_scripts'), type_='foreignkey')
        batch_op.drop_column('script_id')

    # ### end Alembic commands ###
