"""scan schedules, user real name phone, task meta snapshot

Revision ID: 78b35e30ea36
Revises: 1eb13d95d360
Create Date: 2026-08-18 17:24:55.809635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b35e30ea36'
down_revision: Union[str, Sequence[str], None] = '1eb13d95d360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scan_type', sa.String(length=32), nullable=False),
    sa.Column('cron_expr', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_schedules_scan_type'), ['scan_type'], unique=False)

    with op.batch_alter_table('call_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_schedule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meta_json', sa.Text(), nullable=False, server_default=''))
        batch_op.create_foreign_key(op.f('fk_call_tasks_scan_schedule_id_scan_schedules'), 'scan_schedules', ['scan_schedule_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_name', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('real_name')

    with op.batch_alter_table('call_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_call_tasks_scan_schedule_id_scan_schedules'), type_='foreignkey')
        batch_op.drop_column('meta_json')
        batch_op.drop_column('scan_schedule_id')

    with op.batch_alter_table('scan_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_schedules_scan_type'))

    op.drop_table('scan_schedules')
    # ### end Alembic commands ###
