"""link changesets to import batches

Revision ID: b24a633aa108
Revises: fa7af4738103
Create Date: 2026-08-17 18:02:18.938132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24a633aa108'
down_revision: Union[str, Sequence[str], None] = 'fa7af4738103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_change_sets_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_change_sets_import_batch_id', 'import_batches', ['import_batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_sets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_change_sets_import_batch_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_change_sets_import_batch_id'))
        batch_op.drop_column('import_batch_id')

    # ### end Alembic commands ###
