"""initial schema

Revision ID: b4127c1a2567
Revises: 
Create Date: 2026-08-17 13:53:38.756090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4127c1a2567'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_phone'), ['phone'], unique=False)

    op.create_table('custom_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictionary_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tts_status', sa.String(length=32), nullable=False),
    sa.Column('wav_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('callback_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cron_expr', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('callback_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callback_plans_next_run_at'), ['next_run_at'], unique=False)

    op.create_table('change_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('applied_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_sets_status'), ['status'], unique=False)

    op.create_table('custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['custom_field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'entity_type', 'entity_id', name='uq_custom_field_values_target')
    )
    op.create_table('customer_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('duty', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'contact_id', 'duty', name='uq_customer_contacts_link')
    )
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contacts_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_contacts_customer_id'), ['customer_id'], unique=False)

    op.create_table('dictionary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['dictionary_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'code', name='uq_dictionary_items_category_code'),
    sa.UniqueConstraint('category_id', 'label', name='uq_dictionary_items_category_label')
    )
    with op.batch_alter_table('dictionary_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dictionary_items_category_id'), ['category_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', 'domain')
    )
    op.create_table('role_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_value', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'scope_type', 'scope_value', name='uq_role_scopes_binding')
    )
    with op.batch_alter_table('role_scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_scopes_role_id'), ['role_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('business_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_number', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('county_item_id', sa.Integer(), nullable=True),
    sa.Column('grid_item_id', sa.Integer(), nullable=True),
    sa.Column('service_status_item_id', sa.Integer(), nullable=True),
    sa.Column('business_type_item_id', sa.Integer(), nullable=True),
    sa.Column('data_quality_status_item_id', sa.Integer(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreement_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_name', sa.String(length=160), nullable=False),
    sa.Column('source_row', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_type_item_id'], ['dictionary_items.id'], ),
    sa.ForeignKeyConstraint(['county_item_id'], ['dictionary_items.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['data_quality_status_item_id'], ['dictionary_items.id'], ),
    sa.ForeignKeyConstraint(['grid_item_id'], ['dictionary_items.id'], ),
    sa.ForeignKeyConstraint(['service_status_item_id'], ['dictionary_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_services_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_services_service_number'), ['service_number'], unique=True)

    op.create_table('call_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('dial_number', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['callback_plans.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_tasks_status'), ['status'], unique=False)

    op.create_table('change_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_set_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('patch_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_set_id'], ['change_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_items_change_set_id'), ['change_set_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=320), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('header_mapping_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('applied_change_set_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applied_change_set_id'], ['change_sets.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_status'), ['status'], unique=False)

    op.create_table('call_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('dial_number', sa.String(length=32), nullable=False),
    sa.Column('dialing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('operator_feedback', sa.Text(), nullable=False),
    sa.Column('recording_path', sa.String(length=500), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=80), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('ai_result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['callback_plans.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['call_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_records_status'), ['status'], unique=False)

    op.create_table('network_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_service_id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('asset_class_item_id', sa.Integer(), nullable=True),
    sa.Column('asset_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('device_type_item_id', sa.Integer(), nullable=True),
    sa.Column('vendor_model', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=320), nullable=False),
    sa.Column('recovery_status_item_id', sa.Integer(), nullable=True),
    sa.Column('recovery_reason_item_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_contact_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_class_item_id'], ['dictionary_items.id'], ),
    sa.ForeignKeyConstraint(['business_service_id'], ['business_services.id'], ),
    sa.ForeignKeyConstraint(['device_type_item_id'], ['dictionary_items.id'], ),
    sa.ForeignKeyConstraint(['maintenance_contact_id'], ['customer_contacts.id'], ),
    sa.ForeignKeyConstraint(['recovery_reason_item_id'], ['dictionary_items.id'], ),
    sa.ForeignKeyConstraint(['recovery_status_item_id'], ['dictionary_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_devices_business_service_id'), ['business_service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_devices_device_code'), ['device_code'], unique=True)

    op.create_table('staging_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_messages', sa.Text(), nullable=False),
    sa.Column('mapped_json', sa.Text(), nullable=False),
    sa.Column('result_entity_type', sa.String(length=64), nullable=False),
    sa.Column('result_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_staging_rows_batch_row')
    )
    with op.batch_alter_table('staging_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staging_rows_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staging_rows_status'), ['status'], unique=False)

    op.create_table('call_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_record_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_record_id'], ['call_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_events_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_call_events_created_at'))

    op.drop_table('call_events')
    with op.batch_alter_table('staging_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staging_rows_status'))
        batch_op.drop_index(batch_op.f('ix_staging_rows_batch_id'))

    op.drop_table('staging_rows')
    with op.batch_alter_table('network_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_devices_device_code'))
        batch_op.drop_index(batch_op.f('ix_network_devices_business_service_id'))

    op.drop_table('network_devices')
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_records_status'))

    op.drop_table('call_records')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_status'))

    op.drop_table('import_batches')
    with op.batch_alter_table('change_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_items_change_set_id'))

    op.drop_table('change_items')
    with op.batch_alter_table('call_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_call_tasks_due_at'))

    op.drop_table('call_tasks')
    with op.batch_alter_table('business_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_services_service_number'))
        batch_op.drop_index(batch_op.f('ix_business_services_customer_id'))

    op.drop_table('business_services')
    op.drop_table('user_roles')
    with op.batch_alter_table('role_scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_scopes_role_id'))

    op.drop_table('role_scopes')
    op.drop_table('role_permissions')
    with op.batch_alter_table('dictionary_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_items_category_id'))

    op.drop_table('dictionary_items')
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_contacts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_contacts_contact_id'))

    op.drop_table('customer_contacts')
    op.drop_table('custom_field_values')
    with op.batch_alter_table('change_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_sets_status'))

    op.drop_table('change_sets')
    with op.batch_alter_table('callback_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callback_plans_next_run_at'))

    op.drop_table('callback_plans')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('scripts')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('dictionary_categories')
    op.drop_table('customers')
    op.drop_table('custom_field_definitions')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_phone'))

    op.drop_table('contacts')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
