"""remove role scopes

Revision ID: fa7af4738103
Revises: 96085cfcc38f
Create Date: 2026-08-17 17:56:41.197376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7af4738103'
down_revision: Union[str, Sequence[str], None] = '96085cfcc38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_scopes_role_id'))

    op.drop_table('role_scopes')
    permission_ids = {
        code: op.get_bind().execute(
            sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": code}
        ).scalar_one()
        for code in ("read", "submit", "review", "apply")
    }
    role_permissions = sa.table(
        "role_permissions",
        sa.column("role_id", sa.Integer),
        sa.column("permission_id", sa.Integer),
        sa.column("domain", sa.String),
    )
    op.bulk_insert(
        role_permissions,
        [
            {"role_id": 5, "permission_id": permission_ids[code], "domain": domain}
            for domain in ("business", "network")
            for code in ("read", "submit", "review", "apply")
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE role_id = 5 "
            "AND domain IN ('business', 'network') "
            "AND permission_id IN (SELECT id FROM permissions WHERE code IN "
            "('read', 'submit', 'review', 'apply'))"
        )
    )
    op.create_table('role_scopes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('scope_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('scope_value', sa.VARCHAR(length=120), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'scope_type', 'scope_value', name=op.f('uq_role_scopes_binding'))
    )
    with op.batch_alter_table('role_scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_scopes_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###
